language: php
os: linux

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - setup=basic
    - coverage=false

branches:
  except:
    - /analysis-.*/

before_install:
  - if [[ $coverage = 'false' ]]; then phpenv config-rm xdebug.ini || true; fi
  - composer global require hirak/prestissimo --update-no-dev

install:
  - if [[ $setup = 'basic'  ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest; fi
  - composer info | grep -e phpunit/phpunit -e phpstan/phpstan

script:
  - if [[ $coverage = 'true' ]]; then composer test-cover; else composer test; fi

after_success:
  - if [[ $coverage = 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi

jobs:
  include:
    - php: 7.1.3
      env: setup=lowest
    - php: 7.1.3
      env: coverage=true

    - php: 7.2
      env: setup=lowest
    - php: 7.2
      env: coverage=true

    - php: 7.3
      env: setup=lowest
    - php: 7.3
      env: coverage=true

    - php: 7.4
      env: setup=lowest
    - php: 7.4
      env: coverage=true
